/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 earth.gltf 
Author: Akshat (https://sketchfab.com/shooter24994)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/earth-41fc80d85dfd480281f21b74b2de2faa
Title: Earth
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Earth() {
    const { nodes, materials } = useGLTF("./earth/scene.gltf");

    return (
        <group rotation={[-Math.PI / 2, 0, 0]}>
            <group rotation={[Math.PI / 2, 0, 0]}>
                <group rotation={[-Math.PI / 2, 0, 0]}>
                    <mesh
                        // ref={meshRef}
                        geometry={nodes.Sphere_Material002_0.geometry}
                        material={materials["./earth/textures/Material.002"]}
                    />
                </group>
            </group>
        </group>
    );
}

useGLTF.preload('/earth/scene.gltf')
